services:
  python:
    container_name: lefiya-schedule-bot
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=Asia/Taipei
    restart: on-failure:3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
